---
title: "Flyer Scraper"
output: html_notebook
---

```{r}
# Install required packages
install.packages("dplyr")
install.packages("RSelenium")
```


```{r}
# Import packages
library(dplyr)
library(RSelenium)

# Waits a random time between a range after css element body is found
wait <- function(sleepmin,sleepmax){
  remDr <- get("rem_driver",envir=globalenv())
  webElemtest <-NULL
  while(is.null(webElemtest)){
    webElemtest <- tryCatch({remDr$findElement(using = 'css', "body")},
                            error = function(e){NULL})
  }
  randsleep <- sample(seq(sleepmin, sleepmax, by = 0.001), 1)
  Sys.sleep(randsleep)
}

# Return a list of elements found at the link using an element type and value
getDetailElements <- function(link, using, value){
  elements <- tryCatch({
    rem_driver$findElements(using = using, value = value)
    },
    error = function(e){
      message(paste(e))
      NULL
    }
  )
  elements
}

# Return element text of the first element in a list of web elements
getElementText <- function(elements){
  if (length(elements) > 0) {
      element_text <- paste(elements[[1]]$getElementText())
    }
    else {
      element_text <- paste("")
    }
  element_text
}

# Return element attribute of the first element in a list of web elements
getElementAttribute <- function(elements){
  if (length(elements) > 0) {
      element_attribute <- paste(elements[[1]]$getElementAttribute("value"))
    }
    else {
      element_attribute <- paste("")
    }
  element_attribute
}
```


```{r}
# Open browser
rem_driver <- remoteDriver(remoteServerAddr = 'localhost',
                           browserName = 'chrome',
                           port=4444L)
rem_driver$open()

rem_driver$setTimeout(type = "implicit", milliseconds = 500)

```


```{r}
# Initialize df
flyers <- tibble(product=character(), 
             quantity=character(), 
             price=character(), 
             weight=character(), 
             description=character(), 
             store=character(), 
             validity=character())
```


```{r}
# List of flyers to find products from
flyer_list <- list()

# Iterate through all flyers in flyer_list, get a list of all products, then add each to the tibble flyers
for (flyer in flyer_list){
  # Navigate to flyer
  rem_driver$navigate(flyer)
  wait(sleepmin=3,sleepmax=5)
  
  # Get store name
  elem_store <- rem_driver$findElements(using = 'class', value='subtitle')
  store_name <- paste(elem_store[[1]]$getElementText())
  
  # Get validity
  elem_validity <- rem_driver$findElements(using = 'class', value='validity')
  validity <- paste(elem_validity[[1]]$getElementText())
  
  # Find products
  elem_products <- rem_driver$findElements(using = 'class', value='item-container')
  wait(sleepmin=3,sleepmax=5)
  product_list = list()
  for (element in elem_products){
    product_list = append(product_list, paste("https://flipp.com", element$getElementAttribute("href"), sep=""))
  }
  
  # Get details of each product and add to database
  for (link in product_list){
    wait(sleepmin=1,sleepmax=2)
    
    # Go to product link
    rem_driver$navigate(link)
    
    # Get name
    found_elements <- getDetailElements(link, 'xpath', '//*[contains(concat( " ", @class, " " ), concat( " ", "title", " " ))]//span')
    product_name <- getElementText(found_elements)
    
    # Get pre price
    found_elements <- getDetailElements(link, 'class', 'pre-price-text')
    product_preprice <- getElementText(found_elements)
    
    # Get price
    found_elements <- getDetailElements(link, 'tag name', 'flipp-price')
    product_price <- getElementAttribute(found_elements)
    
    # Get post price
    found_elements <- getDetailElements(link, 'class', 'price-text')
    product_postprice <- getElementText(found_elements)
    
    # Get Description
    found_elements <- getDetailElements(link, 'xpath', '//*[contains(concat( " ", @class, " " ), concat( " ", "description", " " ))]//span')
    product_desc <- getElementText(found_elements)
    
    # Add to database
    flyers <- flyers %>% add_row(product=product_name, 
                   quantity=product_preprice, 
                   price=product_price, 
                   weight=product_postprice, 
                   description=product_desc, 
                   store=store_name, 
                   validity=validity)
  }
}

# Match quantities ("#/" or "# for"): "^\d[\/\ ]"
# Match units: "[\d\ /.]+[mM][lL]|[\d\ /.]+[gG]|[\d\ /.]+[lL][bB][sS]|[\d\ /.]+[eE][aA]|[\d\ /.]+[uU][nN]|[\d\ /.]+[kK][gG]|[\d\ /.]+[pP][kK][gG]"

```


```{r}
# Remove duplicate entries
flyers_cleaned <- flyers %>% distinct(.keep_all=TRUE)

# Add most recently scraped flyers to all past flyers
combined <- rbind(db2, flyers_cleaned)

# Write all scraped flyers to a csv file
write.table(combined, file = "combined.csv", sep=",", eol="\n", row.names=FALSE, qmethod="double")
```
